server:
  port: 8081
spring:
  application:
    name: picpay
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /dev-h2-console

aws:
  access-key:
  secret-key:
  region: us-east-1
  topic-arn: 

kafka:
  producer:
    topic-error: topic-error